### ISSUE TITLE
syslog output is missing

### ISSUE THREAD

**Issue by s-maynard** [s-maynard/sniff#2]
we don't seem to have a log file...
find out where it goes by default (and change that to /var/log/) or find out how we are misconfiguring it

**Comment by taylor7a** [comment]
the system is configured to use syslog-ng, but right now the init of syslog.ng is failing because of the syntax in the /etc/syslog-ng/syslog-ng.conf

Line 55 has a backtick that is confusing the parser

Once removed, you can cat /var/log/syslog (but still need to use sudo)

NOTE: only tested by modifying the file on a running system, need to check the solution in for the build

**Comment by s-maynard** [comment]
Adam fixed this
